# Generated by Django 3.2.5 on 2021-08-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistlineitem',
            old_name='wishlist',
            new_name='wishlist_id',
        ),
    ]
